### ISSUE TITLE
CRI not running after running ./cka/setup-container.sh 

### ISSUE THREAD

**Issue by nsalfos** [sandervanvugt/cka#12]
```
[root@controller cka]# ./setup-container.sh 
setting up CentOS 7 with Docker
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: download.cf.centos.org
 * extras: download.cf.centos.org
 * updates: download.cf.centos.org
Package 2:vim-enhanced-7.4.629-8.el7_9.x86_64 already installed and latest version
Package yum-utils-1.1.31-54.el7_8.noarch already installed and latest version
Package device-mapper-persistent-data-0.8.5-3.el7_9.2.x86_64 already installed and latest version
Package 7:lvm2-2.02.187-6.el7_9.5.x86_64 already installed and latest version
Nothing to do
Loaded plugins: fastestmirror
adding repo from: https://download.docker.com/linux/centos/docker-ce.repo
grabbing file https://download.docker.com/linux/centos/docker-ce.repo to /etc/yum.repos.d/docker-ce.repo
repo saved to /etc/yum.repos.d/docker-ce.repo
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: download.cf.centos.org
 * extras: download.cf.centos.org
 * updates: download.cf.centos.org
Package 3:docker-ce-20.10.23-3.el7.x86_64 already installed and latest version
Nothing to do
Failed to execute operation: No such file or directory
printing MYOS CentOS

[root@controller cka]# kubeadm init
[init] Using Kubernetes version: v1.26.1
[preflight] Running pre-flight checks
error execution phase preflight: [preflight] Some fatal errors occurred:
        [ERROR CRI]: container runtime is not running: output: time="2023-01-24T17:21:08Z" level=fatal msg="validate service connection: CRI v1 runtime API is not implemented for endpoint \"unix:///var/run/containerd/containerd.sock\": rpc error: code = Unimplemented desc = unknown service runtime.v1.RuntimeService"
, error: exit status 1
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
To see the stack trace of this error execute with --v=5 or higher
[root@controller cka]# 
```

**Comment by danielecazzari** [comment]
I had a similar issue on ubuntu 22.04. It seems that containerd version provided by ubuntu repo is too old for the lasted kubernetes version releases 1 week ago see also: https://kubernetes.io/blog/2022/11/18/upcoming-changes-in-kubernetes-1-26/#cri-api-removal
I solved by manually upgrading the version but maybe sender would suggest a better approach. 
Those are the command I used:
sudo su
wget https://github.com/containerd/containerd/releases/download/v1.6.15/containerd-1.6.15-linux-amd64.tar.gz
tar xvf containerd-1.6.15-linux-amd64.tar.gz
systemctl stop containerd
cd bin
cp * /usr/bin/
systemctl start containerd

**Comment by sandervanvugt** [comment]
Thanks for your much appreciated feedback. I have integrated your solution in the setup-container.sh script, while waiting for a container update to be released in the Ubuntu repositories. Please let me know if you have any additional feedback.

**Comment by nsalfos** [comment]
Hey @sandervanvugt thanks for coming back, it seems you updated the script but left out CentOS completely there.

**Comment by sandervanvugt** [comment]
Sorry, I’ll work on CentOS later and provide a full update. The old code was CentOS 7 only anyway, and I’m too busy now to give that an update as well now.

**Comment by nsalfos** [comment]
@sandervanvugt  no worries, thanks for the quick reply, i'll try to go over the kubernets doc,  document the steps i do and send you PR later.

**Comment by nsalfos** [comment]
@sandervanvugt sent that PR, feel free to check and modify as you please, hope it helps!
