### ISSUE TITLE
suggestion: categorize the yaml files in directories per lesson

### ISSUE THREAD

**Issue by profnandaa** [sandervanvugt/cka#23]
Just a quick suggestion, how about categorizing all these YAML files in the respective lessons as per your CKA course on O'Reilly, e.g. `lesson_10/rolebind.yaml`.
If this is okay with you, I could go ahead and do a PR.

Otherwise, great course and thanks for doing this!

**Comment by sandervanvugt** [comment]
I do like the idea, but I think I should combine that with the new CKA complete video course which I’m going to record later this year. 
At the same time, I’ll also clean up the current Git repo and remove all old files that are no longer used. 

Thanks!
Sander

**Comment by profnandaa** [comment]
sounds great, will be looking forward to it!
